apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uvyfxxqlu-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uvyfxxqlu-java-quarkus-gitops